### ISSUE TITLE
WORM is already supported

### ISSUE THREAD

**Issue by jsuarezs** [NetAppDocs/occm38#9]
Page: [Learn about Backup to Cloud](https://docs.netapp.com/us-en/occm38/concept_backup_to_cloud.html)

Hello team.

In limitations is specifying that WORM is not supported in CBS. However, I think this is already supported, kindly check this one please.

Regards.

**Comment by netapp-bcammett** [comment]
@jsuarezs 
WORM can't be enabled if Cloud Backup is enabled on a Cloud Volumes ONTAP working environment:

![image](https://user-images.githubusercontent.com/18287750/163794592-e53d6d4e-00f6-407e-a411-4f10c136d6b7.png)

**Comment by jsuarezs** [comment]
Thanks Ben, I would check this internally.

Regards.
